<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>cam-occ: src/cam/gcode2Model3d.cpp Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.7.1 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li class="current"><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="files.html"><span>File&nbsp;List</span></a></li>
      <li><a href="globals.html"><span>File&nbsp;Members</span></a></li>
    </ul>
  </div>
<div class="header">
  <div class="headertitle">
<h1>src/cam/gcode2Model3d.cpp</h1>  </div>
</div>
<div class="contents">
<a href="gcode2_model3d_8cpp.html">Go to the documentation of this file.</a><div class="fragment"><pre class="fragment"><a name="l00001"></a>00001 <span class="comment">/***************************************************************************</span>
<a name="l00002"></a>00002 <span class="comment"> *   Copyright (C) 2009 by Mark Pictor                                     *</span>
<a name="l00003"></a>00003 <span class="comment"> *   mpictor@gmail.com                                                     *</span>
<a name="l00004"></a>00004 <span class="comment"> *                                                                         *</span>
<a name="l00005"></a>00005 <span class="comment"> *   This program is free software; you can redistribute it and/or modify  *</span>
<a name="l00006"></a>00006 <span class="comment"> *   it under the terms of the GNU General Public License as published by  *</span>
<a name="l00007"></a>00007 <span class="comment"> *   the Free Software Foundation; either version 2 of the License, or     *</span>
<a name="l00008"></a>00008 <span class="comment"> *   (at your option) any later version.                                   *</span>
<a name="l00009"></a>00009 <span class="comment"> *                                                                         *</span>
<a name="l00010"></a>00010 <span class="comment"> *   This program is distributed in the hope that it will be useful,       *</span>
<a name="l00011"></a>00011 <span class="comment"> *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *</span>
<a name="l00012"></a>00012 <span class="comment"> *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *</span>
<a name="l00013"></a>00013 <span class="comment"> *   GNU General Public License for more details.                          *</span>
<a name="l00014"></a>00014 <span class="comment"> *                                                                         *</span>
<a name="l00015"></a>00015 <span class="comment"> *   You should have received a copy of the GNU General Public License     *</span>
<a name="l00016"></a>00016 <span class="comment"> *   along with this program; if not, write to the                         *</span>
<a name="l00017"></a>00017 <span class="comment"> *   Free Software Foundation, Inc.,                                       *</span>
<a name="l00018"></a>00018 <span class="comment"> *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *</span>
<a name="l00019"></a>00019 <span class="comment"> ***************************************************************************/</span>
<a name="l00020"></a>00020 
<a name="l00021"></a>00021 <span class="comment">//3d stuff for gcode2model</span>
<a name="l00022"></a>00022 
<a name="l00023"></a>00023 <span class="preprocessor">#include &quot;<a class="code" href="gcode2_model_8h.html">gcode2Model.h</a>&quot;</span>
<a name="l00024"></a>00024 <span class="preprocessor">#include &lt;AIS_InteractiveContext.hxx&gt;</span>
<a name="l00025"></a>00025 <span class="preprocessor">#include &lt;AIS_Shape.hxx&gt;</span>
<a name="l00026"></a>00026 <span class="preprocessor">#include &lt;BRepAlgoAPI_Fuse.hxx&gt;</span>
<a name="l00027"></a>00027 <span class="preprocessor">#include &lt;BRepBuilderAPI_MakeWire.hxx&gt;</span>
<a name="l00028"></a>00028 <span class="preprocessor">#include &lt;BRepPrimAPI_MakeBox.hxx&gt;</span>
<a name="l00029"></a>00029 <span class="preprocessor">#include &lt;BRepBuilderAPI_MakeEdge.hxx&gt;</span>
<a name="l00030"></a>00030 <span class="preprocessor">#include &lt;BRepBuilderAPI_MakeFace.hxx&gt;</span>
<a name="l00033"></a>00033 <span class="preprocessor">#include &lt;GCE2d_MakeSegment.hxx&gt;</span>
<a name="l00034"></a>00034 <span class="preprocessor">#include &lt;GeomLProp_CurveTool.hxx&gt;</span>
<a name="l00035"></a>00035 <span class="preprocessor">#include &lt;GeomAPI_ProjectPointOnSurf.hxx&gt;</span>
<a name="l00036"></a>00036 <span class="preprocessor">#include &lt;Geom2d_TrimmedCurve.hxx&gt;</span>
<a name="l00037"></a>00037 <span class="preprocessor">#include &lt;BRepBuilderAPI_Transform.hxx&gt;</span>
<a name="l00038"></a>00038 <span class="preprocessor">#include &lt;BRepAdaptor_Curve.hxx&gt;</span>
<a name="l00039"></a>00039 <span class="preprocessor">#include &lt;BRepOffsetAPI_MakePipeShell.hxx&gt;</span>
<a name="l00040"></a>00040 <span class="preprocessor">#include &lt;BRepBuilderAPI_MakeWire.hxx&gt;</span>
<a name="l00041"></a>00041 <span class="preprocessor">#include &lt;BRep_Tool.hxx&gt;</span> 
<a name="l00042"></a>00042 <span class="preprocessor">#include &lt;Geom_CylindricalSurface.hxx&gt;</span>
<a name="l00043"></a>00043 <span class="preprocessor">#include &lt;gp_Pnt.hxx&gt;</span>
<a name="l00044"></a>00044 <span class="preprocessor">#include &lt;gp_Pln.hxx&gt;</span>
<a name="l00045"></a>00045 <span class="preprocessor">#include &lt;gp_Ax1.hxx&gt;</span>
<a name="l00046"></a>00046 <span class="preprocessor">#include &lt;TopoDS.hxx&gt;</span>
<a name="l00047"></a>00047 <span class="preprocessor">#include &lt;TopoDS_Shape.hxx&gt;</span>
<a name="l00048"></a>00048 <span class="preprocessor">#include &lt;TopoDS_Solid.hxx&gt;</span>
<a name="l00049"></a>00049 <span class="preprocessor">#include &lt;TopExp.hxx&gt;</span>
<a name="l00050"></a>00050 <span class="preprocessor">#include &lt;Handle_Geom2d_TrimmedCurve.hxx&gt;</span>
<a name="l00051"></a>00051 <span class="preprocessor">#include &lt;Handle_Geom_TrimmedCurve.hxx&gt;</span>
<a name="l00052"></a>00052 <span class="preprocessor">#include &lt;Handle_Geom_CylindricalSurface.hxx&gt;</span>
<a name="l00053"></a>00053 <span class="preprocessor">#include &lt;GC_MakeArcOfCircle.hxx&gt;</span>
<a name="l00054"></a>00054 
<a name="l00055"></a>00055 <span class="keyword">using</span> std::cout;
<a name="l00056"></a>00056 
<a name="l00057"></a>00057 <span class="comment">/*</span>
<a name="l00058"></a>00058 <span class="comment">*To create the cross-section of the tool, take a 3d model of it</span>
<a name="l00059"></a>00059 <span class="comment">* and project onto a plane normal to the motion vector.</span>
<a name="l00060"></a>00060 <span class="comment">*Cross section would be useful for linear moves, instantaneous</span>
<a name="l00061"></a>00061 <span class="comment">* outline computation for helical moves in any plane, and arc </span>
<a name="l00062"></a>00062 <span class="comment">* moves in xz or yz plane.</span>
<a name="l00063"></a>00063 <span class="comment">*For arcs in xy plane, simply sweep the cross-section of the tool.</span>
<a name="l00064"></a>00064 <span class="comment">*Despite all the effort put into creating a wire, that really isn&#39;t</span>
<a name="l00065"></a>00065 <span class="comment">* useful - the MRSEVs will have to be calculated individually.</span>
<a name="l00066"></a>00066 <span class="comment">*Create a function that will create a 2d outline of an APT tool.</span>
<a name="l00067"></a>00067 <span class="comment">*hard parts: any shape but ball-nose for non-xy-plane cuts</span>
<a name="l00068"></a>00068 <span class="comment">*need to create a cut-segment ABC and subclass it for linear,</span>
<a name="l00069"></a>00069 <span class="comment">* arc, and helical csegs.</span>
<a name="l00070"></a>00070 <span class="comment">*/</span>
<a name="l00071"></a>00071 <span class="comment">//doesn&#39;t really sweep right now, just displays the wire</span>
<a name="l00072"></a>00072 
<a name="l00073"></a>00073 <span class="comment">/*</span>
<a name="l00074"></a>00074 <span class="comment">BRepOffsetAPI_MakePipeShell (const TopoDS_Wire &amp;Spine)</span>
<a name="l00075"></a>00075 <span class="comment"> ::SetMode (const TopoDS_Wire &amp;AuxiliarySpine, const Standard_Boolean CurvilinearEquivalence, const Standard_Boolean KeepContact=Standard_False)</span>
<a name="l00076"></a>00076 <span class="comment">        Sets an auxiliary spine to define the Normal </span>
<a name="l00077"></a>00077 <span class="comment">        --&gt; does this mean what I think it means? If so, project the segment onto an xy plane, use the result as the aux spine.</span>
<a name="l00078"></a>00078 <span class="comment">                --probably wouldn&#39;t work well, depends on paramaterization of the projected spine vs that of the original</span>
<a name="l00079"></a>00079 <span class="comment">        --&gt; or subclass it and just fix the section as normal to XY</span>
<a name="l00080"></a>00080 <span class="comment">*/</span>
<a name="l00081"></a>00081 <span class="keywordtype">void</span> gcode2Model::sweep()
<a name="l00082"></a>00082 {
<a name="l00083"></a>00083         <span class="keywordtype">bool</span> ready = <span class="keyword">false</span>;
<a name="l00084"></a>00084         Handle_AIS_Shape pipeAis;
<a name="l00085"></a>00085         TopoDS_Wire toolwire = create2dTool(1,0);
<a name="l00086"></a>00086         TopoDS_Face tool2d = BRepBuilderAPI_MakeFace(gp_Pln(gp::ZOX()),toolwire);
<a name="l00087"></a>00087 
<a name="l00088"></a>00088         drawSome(-1);
<a name="l00089"></a>00089 
<a name="l00090"></a>00090         <span class="comment">//place the tool at the start of the wire and in the correct orientation</span>
<a name="l00091"></a>00091 <span class="comment">/*      gp_Trsf fTrsf;</span>
<a name="l00092"></a>00092 <span class="comment">        BRepBuilderAPI_Transform brepTrsf(tool2d , fTrsf);</span>
<a name="l00093"></a>00093 <span class="comment">        TopoDS_Shape trsfShape = brepTrsf.Shape();</span>
<a name="l00094"></a>00094 <span class="comment">        TopoDS_Face sweepFace = TopoDS::Face(trsfShape);</span>
<a name="l00095"></a>00095 <span class="comment">*/</span>
<a name="l00096"></a>00096         BRepOffsetAPI_MakePipeShell pipe(thePath);
<a name="l00097"></a>00097         <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;pipe&quot;</span>);
<a name="l00098"></a>00098         pipe.Add(toolwire,<span class="keyword">false</span>,<span class="keyword">true</span>);
<a name="l00099"></a>00099         <span class="comment">//pipe.Add(tool2d,false,true);</span>
<a name="l00100"></a>00100         <span class="comment">//pipe.SetTransitionMode()</span>
<a name="l00101"></a>00101         <span class="comment">//pipe.SetMode()</span>
<a name="l00102"></a>00102         <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;added tool\n&quot;</span>);
<a name="l00103"></a>00103         <span class="keywordflow">if</span> ( pipe.IsReady() ) {
<a name="l00104"></a>00104                 pipe.Build();
<a name="l00105"></a>00105                 BRepBuilderAPI_PipeError error = pipe.GetStatus();
<a name="l00106"></a>00106                 <span class="keywordflow">switch</span> (error) {
<a name="l00107"></a>00107                   <span class="keywordflow">case</span> BRepBuilderAPI_PipeNotDone:
<a name="l00108"></a>00108                     <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;Pipe not done&quot;</span>);
<a name="l00109"></a>00109                     <span class="keywordflow">break</span>;
<a name="l00110"></a>00110                   <span class="keywordflow">case</span> BRepBuilderAPI_PlaneNotIntersectGuide:
<a name="l00111"></a>00111                     <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;Pipe not intersect guide&quot;</span>);
<a name="l00112"></a>00112                     <span class="keywordflow">break</span>;
<a name="l00113"></a>00113                   <span class="keywordflow">case</span> BRepBuilderAPI_ImpossibleContact:
<a name="l00114"></a>00114                     <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;Pipe impossible contact&quot;</span>);
<a name="l00115"></a>00115                     <span class="keywordflow">break</span>;
<a name="l00116"></a>00116                   <span class="keywordflow">case</span> BRepBuilderAPI_PipeDone:
<a name="l00117"></a>00117                     ready = <span class="keyword">true</span>;
<a name="l00118"></a>00118                     <span class="keywordflow">break</span>;
<a name="l00119"></a>00119                  <span class="keywordflow">default</span>:
<a name="l00120"></a>00120                     <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;Pipe switch default?!&quot;</span>);
<a name="l00121"></a>00121                 }
<a name="l00122"></a>00122         }
<a name="l00123"></a>00123         <span class="keywordflow">if</span> (ready) {
<a name="l00124"></a>00124                 pipeAis = <span class="keyword">new</span> AIS_Shape ( pipe.Shape() );
<a name="l00125"></a>00125         }<span class="keywordflow">else</span> {
<a name="l00126"></a>00126                 <a class="code" href="classui_stuff.html#a4d9042f009647dd228ab8b4549cd30f9">infoMsg</a>(<span class="stringliteral">&quot;pipe not ready!&quot;</span>);
<a name="l00127"></a>00127                 pipeAis = <span class="keyword">new</span> AIS_Shape ( tool2d );
<a name="l00128"></a>00128         }
<a name="l00129"></a>00129         <a class="code" href="classui_stuff.html#a89a26ae5e922e6f81b9a3c7d285746b8">theWindow</a>-&gt;<a class="code" href="class_qocc_harness_window.html#a82151cae1142a8a91d9bb6b976178eba">getContext</a>()-&gt;SetMaterial ( pipeAis,Graphic3d_NOM_PLASTIC );  <span class="comment">//Try GOLD or PLASTER or ...</span>
<a name="l00130"></a>00130         <a class="code" href="classui_stuff.html#a89a26ae5e922e6f81b9a3c7d285746b8">theWindow</a>-&gt;<a class="code" href="class_qocc_harness_window.html#a82151cae1142a8a91d9bb6b976178eba">getContext</a>()-&gt;SetDisplayMode ( pipeAis,1,Standard_False );  <span class="comment">//shaded</span>
<a name="l00131"></a>00131         <a class="code" href="classui_stuff.html#a89a26ae5e922e6f81b9a3c7d285746b8">theWindow</a>-&gt;<a class="code" href="class_qocc_harness_window.html#a82151cae1142a8a91d9bb6b976178eba">getContext</a>()-&gt;Display ( pipeAis );
<a name="l00132"></a>00132 }
<a name="l00133"></a>00133 
<a name="l00134"></a>00134 <span class="comment">/*void gcode2Model::showWire()</span>
<a name="l00135"></a>00135 <span class="comment"></span>
<a name="l00136"></a>00136 <span class="comment">  //TODO:</span>
<a name="l00137"></a>00137 <span class="comment">  //change this function to display as much as it can, i.e.</span>
<a name="l00138"></a>00138 <span class="comment">  //create wire. if it fails, show the wire up to the failure. if it doesn&#39;t fail,</span>
<a name="l00139"></a>00139 <span class="comment">  //create sweep. if sweep fails, show the wire instead</span>
<a name="l00140"></a>00140 <span class="comment">        gp_Pnt p;</span>
<a name="l00141"></a>00141 <span class="comment">        gp_Vec V;</span>
<a name="l00142"></a>00142 <span class="comment">        gp_Dir dir;</span>
<a name="l00143"></a>00143 <span class="comment">        gp_Ax1 zAxis(gp_Pnt(0,0,0),gp_Dir(0,0,1));</span>
<a name="l00144"></a>00144 <span class="comment">        Standard_Real diam = 1;</span>
<a name="l00145"></a>00145 <span class="comment">        Standard_Real shape = 0;</span>
<a name="l00146"></a>00146 <span class="comment">        TopoDS_Wire toolwire = create2dTool(diam,shape);</span>
<a name="l00147"></a>00147 <span class="comment">        TopoDS_Face tool2d = BRepBuilderAPI_MakeFace(gp_Pln(gp::ZOX()),toolwire);</span>
<a name="l00148"></a>00148 <span class="comment"></span>
<a name="l00149"></a>00149 <span class="comment">        feedSweeps.Nullify();</span>
<a name="l00150"></a>00150 <span class="comment">        traverseSweeps.Nullify();</span>
<a name="l00151"></a>00151 <span class="comment"></span>
<a name="l00152"></a>00152 <span class="comment">        BRepBuilderAPI_MakeWire makeW;</span>
<a name="l00153"></a>00153 <span class="comment"></span>
<a name="l00154"></a>00154 <span class="comment">        for ( uint i=0;i &lt; feedEdges.size();i++ ) {</span>
<a name="l00155"></a>00155 <span class="comment">                checkEdge( feedEdges, i );      //check that edges are connected</span>
<a name="l00156"></a>00156 <span class="comment">                //infoMsg(&quot;ready?&quot;);</span>
<a name="l00157"></a>00157 <span class="comment">                makeW.Add(feedEdges[i].e);</span>
<a name="l00158"></a>00158 <span class="comment">                //assert(makeW.IsDone());</span>
<a name="l00159"></a>00159 <span class="comment">        }</span>
<a name="l00160"></a>00160 <span class="comment">        if (makeW.IsDone()) {</span>
<a name="l00161"></a>00161 <span class="comment">                Handle_AIS_Shape feedAis = new AIS_Shape ( makeW.Wire() );</span>
<a name="l00162"></a>00162 <span class="comment">                theWindow-&gt;getContext()-&gt;SetMaterial ( feedAis,Graphic3d_NOM_PLASTIC );  //Supposed to look like plastic.  Try GOLD or PLASTER or ...</span>
<a name="l00163"></a>00163 <span class="comment">                theWindow-&gt;getContext()-&gt;SetDisplayMode ( feedAis,1,Standard_False );  //shaded</span>
<a name="l00164"></a>00164 <span class="comment">                theWindow-&gt;getContext()-&gt;Display ( feedAis );</span>
<a name="l00165"></a>00165 <span class="comment">        } else {</span>
<a name="l00166"></a>00166 <span class="comment">                cout &lt;&lt; &quot;Failed to build wire from &quot; &lt;&lt; feedEdges.size() &lt;&lt; &quot; segments!&quot; &lt;&lt; endl;</span>
<a name="l00167"></a>00167 <span class="comment">                //infoMsg( QString(&quot;Failed to build wire from &quot;) + int(feedEdges.size()) + &quot; segments!&quot;);</span>
<a name="l00168"></a>00168 <span class="comment">        }</span>
<a name="l00169"></a>00169 <span class="comment"></span>
<a name="l00170"></a>00170 <span class="comment">}*/</span>
<a name="l00171"></a>00171 <span class="keywordtype">void</span> gcode2Model::showWire() {
<a name="l00172"></a>00172         Handle_AIS_Shape feedAis = <span class="keyword">new</span> AIS_Shape ( thePath );
<a name="l00173"></a>00173         <a class="code" href="classui_stuff.html#a89a26ae5e922e6f81b9a3c7d285746b8">theWindow</a>-&gt;<a class="code" href="class_qocc_harness_window.html#a82151cae1142a8a91d9bb6b976178eba">getContext</a>()-&gt;SetMaterial ( feedAis,Graphic3d_NOM_PLASTIC );  <span class="comment">//Supposed to look like plastic.  Try GOLD or PLASTER or ...</span>
<a name="l00174"></a>00174         <a class="code" href="classui_stuff.html#a89a26ae5e922e6f81b9a3c7d285746b8">theWindow</a>-&gt;<a class="code" href="class_qocc_harness_window.html#a82151cae1142a8a91d9bb6b976178eba">getContext</a>()-&gt;SetDisplayMode ( feedAis,1,Standard_False );  <span class="comment">//shaded</span>
<a name="l00175"></a>00175         <a class="code" href="classui_stuff.html#a89a26ae5e922e6f81b9a3c7d285746b8">theWindow</a>-&gt;<a class="code" href="class_qocc_harness_window.html#a82151cae1142a8a91d9bb6b976178eba">getContext</a>()-&gt;Display ( feedAis );
<a name="l00176"></a>00176 }
<a name="l00177"></a>00177 
<a name="l00178"></a>00178 <span class="keywordtype">bool</span> gcode2Model::drawSome(<span class="keywordtype">int</span> j)
<a name="l00179"></a>00179 {
<a name="l00180"></a>00180         <span class="keywordtype">bool</span> success = <span class="keyword">false</span>;
<a name="l00181"></a>00181         <span class="keywordflow">if</span> ( j == -1 ) j += feedEdges.size();
<a name="l00182"></a>00182         <span class="keywordflow">if</span> (j &lt; (<span class="keywordtype">int</span>)feedEdges.size()) {
<a name="l00183"></a>00183                 BRepBuilderAPI_MakeWire makeW;
<a name="l00184"></a>00184                 uint i;
<a name="l00185"></a>00185                 chkEdgeStruct result;
<a name="l00186"></a>00186                 <span class="keywordflow">for</span> ( i=0 ; (int)i &lt; j ; i++ ) {
<a name="l00187"></a>00187                         result = checkEdge( feedEdges, i );     <span class="comment">//check that edges are connected</span>
<a name="l00188"></a>00188                         <span class="keywordflow">if</span> ((result.startGap == 0.0) &amp;&amp; (result.endGap == 0.0))
<a name="l00189"></a>00189                                 makeW.Add(feedEdges[i].e);
<a name="l00190"></a>00190                         <span class="keywordflow">else</span> <span class="keywordflow">return</span> <span class="keyword">false</span>;
<a name="l00191"></a>00191                 }
<a name="l00192"></a>00192                 <span class="keywordflow">if</span> (makeW.IsDone()) {
<a name="l00193"></a>00193                         thePath = makeW.Wire();
<a name="l00194"></a>00194                         success = <span class="keyword">true</span>;
<a name="l00195"></a>00195                 } <span class="keywordflow">else</span> {
<a name="l00196"></a>00196                         cout &lt;&lt; <span class="stringliteral">&quot;Failed to build wire of length &quot;</span> &lt;&lt; j &lt;&lt; endl;
<a name="l00197"></a>00197                         <span class="keywordflow">if</span> ( j &gt; 1 ) {
<a name="l00198"></a>00198                                 cout &lt;&lt; <span class="stringliteral">&quot;last edge: &quot;</span> &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(feedEdges[i-1].start).toStdString() &lt;&lt; <span class="stringliteral">&quot; to &quot;</span>;
<a name="l00199"></a>00199                                 cout &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(feedEdges[i-1].end).toStdString() &lt;&lt; endl;
<a name="l00200"></a>00200                                 cout &lt;&lt; <span class="stringliteral">&quot;prev edge: &quot;</span> &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(feedEdges[i-2].start).toStdString() &lt;&lt; <span class="stringliteral">&quot; to &quot;</span>;
<a name="l00201"></a>00201                                 cout &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(feedEdges[i-2].end).toStdString() &lt;&lt; endl;
<a name="l00202"></a>00202                                 <span class="keywordflow">return</span> drawSome (j-1);
<a name="l00203"></a>00203                         }
<a name="l00204"></a>00204                 }
<a name="l00205"></a>00205         } <span class="keywordflow">else</span> {
<a name="l00206"></a>00206                 cout &lt;&lt; <span class="stringliteral">&quot;past end of feedEdges: index &quot;</span> &lt;&lt; j &lt;&lt; <span class="stringliteral">&quot; is too big for count &quot;</span> &lt;&lt; feedEdges.size() &lt;&lt; endl;
<a name="l00207"></a>00207 <span class="comment">//              infoMsg(s);</span>
<a name="l00208"></a>00208         }
<a name="l00209"></a>00209         <span class="keywordflow">return</span> success;
<a name="l00210"></a>00210 }
<a name="l00211"></a>00211 
<a name="l00212"></a>00212 <span class="comment">/****************************************************************************</span>
<a name="l00213"></a>00213 <span class="comment">TopoDS_Wire create2dTool(Standard_Real diam, Standard_Real shape)</span>
<a name="l00214"></a>00214 <span class="comment"></span>
<a name="l00215"></a>00215 <span class="comment">Returns a wire that is a cross-section of the described tool, for sweeping along toolpath.</span>
<a name="l00216"></a>00216 <span class="comment">diam is the diameter (units ???)</span>
<a name="l00217"></a>00217 <span class="comment">shape controls the tool&#39;s tip as such:</span>
<a name="l00218"></a>00218 <span class="comment">  shape==0   -&gt;  ball nose mill</span>
<a name="l00219"></a>00219 <span class="comment">  shape&gt;=PI  -&gt;  endmill (square tip) (PI radians is 180 degrees, think of it as flat)</span>
<a name="l00220"></a>00220 <span class="comment">  0&lt;shape&lt;PI -&gt;  engraving tool, value is the included angle in RADIANS</span>
<a name="l00221"></a>00221 <span class="comment"></span>
<a name="l00222"></a>00222 <span class="comment">Wire that is returned MUST be on the XZ plane, symmeteric about Z, center of the tooltip at the origin, rest of the tool above (+Z) the origin</span>
<a name="l00223"></a>00223 <span class="comment">******************************************************************************/</span>
<a name="l00224"></a>00224 TopoDS_Wire gcode2Model::create2dTool ( Standard_Real diam, Standard_Real shape ) 
<a name="l00225"></a>00225 {
<a name="l00226"></a>00226         TopoDS_Wire tool2d;
<a name="l00227"></a>00227 
<a name="l00228"></a>00228         <span class="keywordflow">if</span> (shape==0) { <span class="comment">//ballnose mill -- need arc, 3 lines</span>
<a name="l00229"></a>00229                 <span class="comment">//puts(&quot;ball tool&quot;);</span>
<a name="l00230"></a>00230                 Handle(Geom_TrimmedCurve) Tc = GC_MakeArcOfCircle (gp_Pnt(diam/2,0,diam/2), gp_Pnt(0,0,0), gp_Pnt(-diam/2,0,diam/2));
<a name="l00231"></a>00231                 TopoDS_Edge Ec = BRepBuilderAPI_MakeEdge(Tc);  <span class="comment">//convert the curve from geometry to topology</span>
<a name="l00232"></a>00232                 TopoDS_Edge E1 = BRepBuilderAPI_MakeEdge(gp_Pnt(diam/2,0,diam/2), gp_Pnt(diam/2,0,diam*10));
<a name="l00233"></a>00233                 TopoDS_Edge E2 = BRepBuilderAPI_MakeEdge(gp_Pnt(-diam/2,0,diam/2), gp_Pnt(-diam/2,0,diam*10));
<a name="l00234"></a>00234                 TopoDS_Edge E3 = BRepBuilderAPI_MakeEdge(gp_Pnt(-diam/2,0,diam*10), gp_Pnt(diam/2,0,diam*10));
<a name="l00235"></a>00235                 tool2d = BRepBuilderAPI_MakeWire(Ec,E1,E2,E3); <span class="comment">//.Wire();</span>
<a name="l00236"></a>00236         } else if (shape&gt;=PI) { <span class="comment">//endmill -- need rectangle</span>
<a name="l00237"></a>00237                 <span class="comment">//puts(&quot;endmill&quot;);</span>
<a name="l00238"></a>00238                 TopoDS_Edge E1 = BRepBuilderAPI_MakeEdge(gp_Pnt(diam/2,0,0), gp_Pnt(diam/2,0,diam*10));
<a name="l00239"></a>00239                 TopoDS_Edge E2 = BRepBuilderAPI_MakeEdge(gp_Pnt(-diam/2,0,0), gp_Pnt(-diam/2,0,diam*10));
<a name="l00240"></a>00240                 TopoDS_Edge E3 = BRepBuilderAPI_MakeEdge(gp_Pnt(-diam/2,0,0), gp_Pnt(diam/2,0,0));
<a name="l00241"></a>00241                 TopoDS_Edge E4 = BRepBuilderAPI_MakeEdge(gp_Pnt(diam/2,0,diam*10), gp_Pnt(-diam/2,0,diam*10));
<a name="l00242"></a>00242                 tool2d = BRepBuilderAPI_MakeWire(E1,E3,E2,E4); <span class="comment">//apparently the lines have to be in order or it will silently fail?!</span>
<a name="l00243"></a>00243 
<a name="l00244"></a>00244         } <span class="keywordflow">else</span> {  <span class="comment">//V-tip engraving tool -- need V, 3 more lines.</span>
<a name="l00245"></a>00245                 <span class="comment">//puts(&quot;engraving&quot;);</span>
<a name="l00246"></a>00246                 Standard_Real Vz = diam/(2*tan(shape/2)); <span class="comment">//Vz is Z height of top of angled part of tip.</span>
<a name="l00247"></a>00247                 BRepBuilderAPI_MakeWire toolMakeWire;
<a name="l00248"></a>00248                         <span class="comment">//again, wires must be in order, wtf?</span>
<a name="l00249"></a>00249                 toolMakeWire.Add(BRepBuilderAPI_MakeEdge(gp_Pnt(0,0,0), gp_Pnt(diam/2,0,Vz)));  
<a name="l00250"></a>00250                 toolMakeWire.Add(BRepBuilderAPI_MakeEdge(gp_Pnt(0,0,0), gp_Pnt(-diam/2,0,Vz)));
<a name="l00251"></a>00251                 toolMakeWire.Add(BRepBuilderAPI_MakeEdge(gp_Pnt(-diam/2,0,Vz), gp_Pnt(-diam/2,0,diam*10)));
<a name="l00252"></a>00252                 toolMakeWire.Add(BRepBuilderAPI_MakeEdge(gp_Pnt(-diam/2,0,diam*10), gp_Pnt(diam/2,0,diam*10)));
<a name="l00253"></a>00253                 toolMakeWire.Add(BRepBuilderAPI_MakeEdge(gp_Pnt(diam/2,0,Vz), gp_Pnt(diam/2,0,diam*10)));
<a name="l00254"></a>00254                 tool2d = toolMakeWire.Wire();
<a name="l00255"></a>00255         }
<a name="l00256"></a>00256 
<a name="l00257"></a>00257         <span class="keywordflow">return</span> tool2d;
<a name="l00258"></a>00258 }
<a name="l00259"></a>00259 
<a name="l00260"></a>00260 <span class="comment">//begin, direction at begin, end</span>
<a name="l00261"></a>00261 TopoDS_Edge gcode2Model::arc ( gp_Pnt a, gp_Vec V, gp_Pnt b )
<a name="l00262"></a>00262 {
<a name="l00263"></a>00263         Handle ( Geom_TrimmedCurve ) Tc = GC_MakeArcOfCircle ( a, V, b );
<a name="l00264"></a>00264         return BRepBuilderAPI_MakeEdge ( Tc );
<a name="l00265"></a>00265 }
<a name="l00266"></a>00266 
<a name="l00267"></a>00267 <span class="comment">//Create a helix.  Axis MUST be parallel to X, Y, or Z. Create as lines on a cylindrical face (like the makebottle demo)</span>
<a name="l00268"></a>00268 TopoDS_Edge <a class="code" href="classgcode2_model.html">gcode2Model</a>::helix ( gp_Pnt start, gp_Pnt end, gp_Pnt c, gp_Dir dir, <span class="keywordtype">int</span> rot )
<a name="l00269"></a>00269 {
<a name="l00270"></a>00270         Standard_Real pU,pV;
<a name="l00271"></a>00271         Standard_Real radius = start.Distance(c);
<a name="l00272"></a>00272         gp_Pnt2d p1,p2;
<a name="l00273"></a>00273         Handle(Geom_CylindricalSurface) cyl = new Geom_CylindricalSurface(gp_Ax2(c,dir) , radius);
<a name="l00274"></a>00274         GeomAPI_ProjectPointOnSurf proj;
<a name="l00275"></a>00275         TopoDS_Edge h;
<a name="l00276"></a>00276         <span class="keywordtype">int</span> success = 0;
<a name="l00277"></a>00277         
<a name="l00278"></a>00278         h.Nullify();
<a name="l00279"></a>00279         <span class="comment">//cout &lt;&lt; &quot;Radius &quot; &lt;&lt; radius &lt;&lt; &quot;   Rot has the value &quot; &lt;&lt; rot &lt;&lt; endl;</span>
<a name="l00280"></a>00280         proj.Init(start,cyl);
<a name="l00281"></a>00281         if(proj.NbPoints() &gt; 0) {
<a name="l00282"></a>00282                 proj.LowerDistanceParameters(pU, pV);
<a name="l00283"></a>00283                 <span class="keywordflow">if</span>(proj.LowerDistance() &gt; 1.0e-6 ) {
<a name="l00284"></a>00284                         <span class="comment">//cout &lt;&lt; &quot;Point fitting distance &quot; &lt;&lt; double(proj.LowerDistance()) &lt;&lt; endl;</span>
<a name="l00285"></a>00285                 }
<a name="l00286"></a>00286                 success++;
<a name="l00287"></a>00287                 p1 = gp_Pnt2d(pU,pV);
<a name="l00288"></a>00288         }
<a name="l00289"></a>00289         
<a name="l00290"></a>00290         proj.Init(end,cyl);
<a name="l00291"></a>00291         <span class="keywordflow">if</span>(proj.NbPoints() &gt; 0) {
<a name="l00292"></a>00292                 proj.LowerDistanceParameters(pU, pV);
<a name="l00293"></a>00293                 <span class="keywordflow">if</span>(proj.LowerDistance() &gt; 1.0e-6 ) {
<a name="l00294"></a>00294                         <span class="comment">//cout &lt;&lt; &quot;Point fitting distance &quot; &lt;&lt; double(proj.LowerDistance()) &lt;&lt; endl;</span>
<a name="l00295"></a>00295                 }
<a name="l00296"></a>00296                 success++;
<a name="l00297"></a>00297                 p2 = gp_Pnt2d(pU,pV);
<a name="l00298"></a>00298         }
<a name="l00299"></a>00299         
<a name="l00300"></a>00300         <span class="keywordflow">if</span> (success != 2) {
<a name="l00301"></a>00301           cout &lt;&lt; <span class="stringliteral">&quot;Couldn&#39;t create a helix from &quot;</span> &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(start).toStdString() &lt;&lt; <span class="stringliteral">&quot; to &quot;</span> &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(end).toStdString() &lt;&lt; <span class="stringliteral">&quot;. Replacing with a line.&quot;</span> &lt;&lt;endl;
<a name="l00302"></a>00302           h = BRepBuilderAPI_MakeEdge( start, end );
<a name="l00303"></a>00303           <span class="keywordflow">return</span> h;
<a name="l00304"></a>00304         }
<a name="l00305"></a>00305 
<a name="l00306"></a>00306         <span class="comment">//for the 2d points, x axis is about the circumference.  Units are radians.</span>
<a name="l00307"></a>00307         <span class="comment">//change direction if rot = 1, not if rot = -1</span>
<a name="l00308"></a>00308         <span class="comment">//if (rot==1) p2.SetX((p1.X()-p2.X())-2*M_PI); &lt;&lt; this is wrong!</span>
<a name="l00309"></a>00309         <span class="comment">//cout &lt;&lt; &quot;p1x &quot; &lt;&lt; p1.X() &lt;&lt; &quot;, p2x &quot; &lt;&lt; p2.X() &lt;&lt; endl;</span>
<a name="l00310"></a>00310 
<a name="l00311"></a>00311         <span class="comment">//switch direction if necessary, only works for simple cases</span>
<a name="l00312"></a>00312         <span class="comment">//should always work for G02/G03 because they are less than 1 rotation</span>
<a name="l00313"></a>00313         <span class="keywordflow">if</span> (rot==1) {
<a name="l00314"></a>00314           p2.SetX(p2.X()-2*M_PI);
<a name="l00315"></a>00315           <span class="comment">//cout &lt;&lt; &quot;p2x now &quot; &lt;&lt; p2.X() &lt;&lt; endl;</span>
<a name="l00316"></a>00316         }
<a name="l00317"></a>00317         Handle(Geom2d_TrimmedCurve) segment = GCE2d_MakeSegment(p1 , p2);
<a name="l00318"></a>00318         h = BRepBuilderAPI_MakeEdge(segment , cyl);
<a name="l00319"></a>00319         
<a name="l00320"></a>00320         return h;
<a name="l00321"></a>00321 }
<a name="l00322"></a>00322 
<a name="l00323"></a>00323 <span class="comment">//returns a structure containing info on the start and end of the edge</span>
<a name="l00324"></a>00324 <a class="code" href="classgcode2_model.html">gcode2Model</a>::chkEdgeStruct <a class="code" href="classgcode2_model.html">gcode2Model</a>::checkEdge( std::vector&lt;myEdgeType&gt; edges, uint n )
<a name="l00325"></a>00325 {
<a name="l00326"></a>00326   chkEdgeStruct eStruct;
<a name="l00327"></a>00327   eStruct.startGap = 0.0;
<a name="l00328"></a>00328   eStruct.endGap = 0.0;
<a name="l00329"></a>00329   <span class="comment">//if (n &lt; 1) return eStruct;</span>
<a name="l00330"></a>00330   <span class="keywordtype">double</span> d = 0;
<a name="l00331"></a>00331   gp_Pnt p;
<a name="l00332"></a>00332   <span class="keywordtype">bool</span> nogap = <span class="keyword">true</span>;
<a name="l00333"></a>00333   <span class="comment">/* </span>
<a name="l00334"></a>00334 <span class="comment">  ** should not need to check this, start should always be </span>
<a name="l00335"></a>00335 <span class="comment">  ** assigned the value of the previus end.</span>
<a name="l00336"></a>00336 <span class="comment">  d = edges[n].start.Distance(edges[n-1].end);</span>
<a name="l00337"></a>00337 <span class="comment">  if (d &gt; Precision::Confusion()) {</span>
<a name="l00338"></a>00338 <span class="comment">    cout &lt;&lt; &quot;Found gap of &quot; &lt;&lt; d &lt;&lt; &quot; before edge &quot; &lt;&lt; n &lt;&lt; endl;</span>
<a name="l00339"></a>00339 <span class="comment">    nogap = false;</span>
<a name="l00340"></a>00340 <span class="comment">  }</span>
<a name="l00341"></a>00341 <span class="comment">  */</span>
<a name="l00342"></a>00342   
<a name="l00343"></a>00343   p = BRep_Tool::Pnt(TopExp::FirstVertex(edges[n].e));
<a name="l00344"></a>00344   d = edges[n].start.Distance(p);
<a name="l00345"></a>00345   <span class="keywordflow">if</span> (d &gt; Precision::Confusion()) {
<a name="l00346"></a>00346     cout &lt;&lt; <span class="stringliteral">&quot;Start data differs by &quot;</span> &lt;&lt; d &lt;&lt; <span class="stringliteral">&quot; before edge &quot;</span> &lt;&lt; n &lt;&lt; <span class="stringliteral">&quot; - expected: &quot;</span>;
<a name="l00347"></a>00347     cout &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(feedEdges[n].start).toStdString();
<a name="l00348"></a>00348     cout &lt;&lt; <span class="stringliteral">&quot; - actual: &quot;</span> &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(p).toStdString() &lt;&lt; endl;
<a name="l00349"></a>00349     nogap = <span class="keyword">false</span>;
<a name="l00350"></a>00350     eStruct.startGap = d;
<a name="l00351"></a>00351     eStruct.realStart = p;
<a name="l00352"></a>00352   }
<a name="l00353"></a>00353   
<a name="l00354"></a>00354   p = BRep_Tool::Pnt(TopExp::LastVertex(edges[n].e));
<a name="l00355"></a>00355   d = edges[n].end.Distance(p);
<a name="l00356"></a>00356   <span class="keywordflow">if</span> (d &gt; Precision::Confusion()) {
<a name="l00357"></a>00357     <span class="comment">//nogap = false;</span>
<a name="l00358"></a>00358     eStruct.endGap = d;
<a name="l00359"></a>00359     eStruct.realEnd = p;
<a name="l00360"></a>00360   }
<a name="l00361"></a>00361   <span class="comment">//stay silent unless the error is relatively large:</span>
<a name="l00362"></a>00362   <span class="comment">// 1/100,000 inch or 1 nanometer depending on units (inch vs mm)</span>
<a name="l00363"></a>00363   <span class="keywordflow">if</span> (d &gt; 100.0*Precision::Confusion()) { 
<a name="l00364"></a>00364     nogap = <span class="keyword">false</span>;
<a name="l00365"></a>00365     cout &lt;&lt; <span class="stringliteral">&quot;End data differs by &quot;</span> &lt;&lt; d &lt;&lt; <span class="stringliteral">&quot; after edge &quot;</span> &lt;&lt; n &lt;&lt; <span class="stringliteral">&quot; - expected: &quot;</span>;
<a name="l00366"></a>00366     cout &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(feedEdges[n].end).toStdString();
<a name="l00367"></a>00367     cout &lt;&lt; <span class="stringliteral">&quot; - actual: &quot;</span> &lt;&lt; <a class="code" href="classui_stuff.html#a55f33f813f5d36400645e1a8ec14e5c0">toString</a>(p).toStdString() &lt;&lt; endl;
<a name="l00368"></a>00368   }  
<a name="l00369"></a>00369   
<a name="l00370"></a>00370   <span class="keywordflow">if</span> (!nogap) {
<a name="l00371"></a>00371     <span class="keywordflow">if</span> (edges[n].shape == HELIX) {
<a name="l00372"></a>00372         cout &lt;&lt; <span class="stringliteral">&quot;Failure is on a helix&quot;</span>;
<a name="l00373"></a>00373     } <span class="keywordflow">else</span> <span class="keywordflow">if</span> (edges[n].shape == ARC) {
<a name="l00374"></a>00374         cout &lt;&lt; <span class="stringliteral">&quot;Failure is on an arc&quot;</span>;
<a name="l00375"></a>00375     } <span class="keywordflow">else</span> <span class="keywordflow">if</span> ((edges[n].shape == LINE) &amp;&amp; (edges[n].motion == TRAVERSE )) {
<a name="l00376"></a>00376         cout &lt;&lt; <span class="stringliteral">&quot;Failure is on a rapid traverse&quot;</span>;
<a name="l00377"></a>00377     } <span class="keywordflow">else</span> <span class="keywordflow">if</span> ((edges[n].shape == LINE) &amp;&amp; (edges[n].motion == FEED )) {
<a name="l00378"></a>00378         cout &lt;&lt; <span class="stringliteral">&quot;Failure is on a linear move&quot;</span>;
<a name="l00379"></a>00379     } <span class="keywordflow">else</span> cout &lt;&lt; <span class="stringliteral">&quot;Failure is on a move of undefined type!&quot;</span> &lt;&lt; endl; <span class="comment">//should never get here</span>
<a name="l00380"></a>00380   }
<a name="l00381"></a>00381   <span class="keywordflow">return</span> eStruct;
<a name="l00382"></a>00382 }
</pre></div></div>
</div>
<hr class="footer"/><address class="footer"><small>Generated by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.7.1 </small></address>
</body>
</html>
